### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by RiyaRaj28**

### CODE REVIEW

**Review by Himasnhu-AT — CHANGES_REQUESTED** [review]
Can you add more API's?

Covering more edge cases, like only cookies, or when cookie is returned so on...

**Comment by RiyaRaj28** [comment]
Okay sure

**Review by Himasnhu-AT — APPROVED** [review]

**Review by Himasnhu-AT — APPROVED** [review]

**Comment by Himasnhu-AT** [comment]
@RiyaRaj28 build is failing

**Comment by RiyaRaj28** [comment]
> @RiyaRaj28 build is failing

Okay I'll check

**Comment by RiyaRaj28** [comment]
> @RiyaRaj28 build is failing

I have fixed it, can you try again?

**Pull request merged**
